apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gateway-pool
  namespace: metallb
spec:
  addresses:
    - 10.1.10.180
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: gateway-advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - gateway-pool
