apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkerd-viz-route
  namespace: linkerd-viz
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`linkerd.tequila.megakuul.ch`)
      kind: Rule
      services:
        - name: web
          port: 8084
  tls:
    certResolver: letsencrypt 
