apiVersion: v1
kind: Secret
metadata:
  name: linkerd-identity-issuer
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.issuer_crt | b64enc }}
  tls.key: {{ .Values.issuer_key | b64enc }}
