apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rook-route
  namespace: rook-ceph
spec:
  parentRefs:
    - name: traefik
      namespace: traefik

  hostnames:
    - "rook.tequila.megakuul.ch"

  rules:
    - matches:
        - path: 
            type: PathPrefix
            value: /
      backendRefs:
        - name: rook-ceph-mgr-dashboard-https
          port: 8443
