apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-route
  namespace: rook-ceph
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`rook.tequila.megakuul.ch`)
      kind: Rule
      services:
        - name: rook-ceph-mgr-dashboard-https
          port: 8443
  tls:
    certResolver: letsencrypt 
