apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik 
spec:
  secretName: traefik-cert-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - argocd.tequila.megakuul.ch 
    - dashboard.tequila.megakuul.ch 
    - rook.tequila.megakuul.ch
