apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.2.10
      chart: grafana
      helm:
        values: |
          adminPassword: "blub"
          persistence:
            enabled: true 
            size: 10Gi 
          
          datasources:
            datasources.yaml:
              apiVersion: v1 
              datasources:
                - name: Prometheus
                  type: prometheus 
                  url: http://prometheus-server.monitoring.svc.cluster.local 
                  access: proxy 
                  isDefault: true 
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default

          dashboards:
            default:
              kubernetes:
                gnetId: 15661
                revision: 1
                datasource: Prometheus
              node-exporter:
                gnetId: 1860
                revision: 27
                datasource: Prometheus
    - repoURL: https://github.com/megakuul/tequila
      targetRevision: HEAD
      path: apps/grafana/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
