apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb 
      chart: metallb                            
      targetRevision: 0.15.2
      helm:
        includeCrds: true
    - repoURL: https://github.com/megakuul/tequila
      targetRevision: HEAD
      path: apps/metallb/
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
