apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 5.7.0
      chart: mimir-distributed
    - repoURL: https://github.com/megakuul/tequila
      targetRevision: HEAD
      path: apps/grafana/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
