apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      targetRevision: 1.17.5
      chart: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
