apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 36.3.0
      chart: traefik
      helm:
        valuesObject:
          additionalArguments:
            - "--serversTransport.insecureSkipVerify=true"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.http.tls=true"
            - "--entrypoints.web.address=:80"
            - "--certificatesresolvers.letsencrypt.acme.email=acme@megakuul.ch"
            - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
          crds:
            enabled: true
          providers:
            kubernetesCRD:
              enabled: true
          ports:
            web:
              port: 80
              exposedPort: 80
            websecure:
              port: 443
              exposedPort: 443
              tls:
                enabled: true
          persistence:
            enabled: true
            name: data
            accessMode: ReadWriteOnce
            size: 5Mi
            path: /data
          podSecurityContext:
            fsGroup: 65532
            runAsUser: 65532
            runAsGroup: 65532
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
