apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 36.3.0
      chart: traefik
      helm:
        values: |
          additionalArguments:
            - "--certificatesresolvers.letsencrypt.acme.email=linus.moser@megakuul.ch"
            - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
          providers:
            kubernetesGateway:
              enabled: true
          gatewayClass:
            enabled: true
          gateway:
            name: traefik
            listeners:
              web:
                port: 8000
                protocol: HTTP
                namespacePolicy: All
              websecure:
                port: 8443
                protocol: HTTPS
                namespacePolicy: All
                tls:
                  mode: Terminate
                  options:
                    gateway.networking.k8s.io/tls-options: '{"certResolver": "letsencrypt"}'
    - repoURL: https://github.com/megakuul/tequila
      targetRevision: HEAD
      path: apps/traefik/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
