apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 36.3.0
      chart: traefik
      helm:
        values: |
          additionalArguments:
            - "--certificatesresolvers.letsencrypt.acme.email=linus.moser@megakuul.ch"
            - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.http.tls=true"
            
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
          crds:
            enabled: true
          providers:
            kubernetesCRD:
              enabled: true
          ports:
            web:
              port: 80
              exposedPort: 80

            websecure:
              port: 443
              exposedPort: 443
              tls:
                enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
