apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 36.1.0
      chart: traefik
      helm:
        values: |
          providers:
            kubernetesGateway:
              enabled: true
          gateway:
            listeners:
              http:
                port: 80
                protocol: HTTP
                namespacePolicy: All
              https:
                port: 443
                protocol: HTTPS
                namespacePolicy: All
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
