apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 36.3.0
      chart: traefik
      helm:
        values: |
          additionalArguments:
            - "--serversTransport.insecureSkipVerify=true"
          providers:
            kubernetesGateway:
              enabled: true
          gateway:
            listeners:
              web:
                port: 8000
                protocol: HTTP
                namespacePolicy: All
              websecure:
                port: 8443
                protocol: HTTPS
                namespacePolicy: All
                mode: Terminate
                certificateRefs:
                  - name: traefik-tls-secret
                    kind: Secret
                    group: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
