apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`grafana.tequila.megakuul.ch`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: letsencrypt 
