apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`argocd.tequila.megakuul.ch`)
      kind: Rule
      services:
        - name: argo-cd-argocd-server
          port: 443
  tls:
    certResolver: letsencrypt 
